# Generated by Django 3.2.7 on 2021-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('member_pw', models.TextField()),
                ('member_name', models.CharField(max_length=45)),
                ('member_nickname', models.CharField(max_length=45, unique=True)),
                ('member_auth', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=45)),
                ('event_location', models.CharField(max_length=45)),
                ('event_reporting_date', models.DateTimeField(auto_now_add=True)),
                ('event_views', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='MemberAdmin',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.member')),
                ('member_admin_position', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'member_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.member')),
                ('member_user_birth', models.CharField(blank=True, max_length=45, null=True)),
                ('member_user_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('member_user_email', models.CharField(blank=True, max_length=45, null=True)),
                ('member_user_location', models.CharField(blank=True, max_length=45, null=True)),
                ('member_user_num_of_family', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'member_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.event')),
                ('event_management', models.CharField(blank=True, max_length=45, null=True)),
                ('event_period_start', models.DateField(blank=True, null=True)),
                ('event_period_end', models.DateField(blank=True, null=True)),
                ('event_url', models.CharField(blank=True, max_length=45, null=True)),
                ('event_image_url', models.CharField(blank=True, max_length=45, null=True)),
                ('event_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_detail',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.member')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_content', models.TextField()),
                ('notice_views', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.memberadmin')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.memberadmin'),
        ),
    ]
