# Generated by Django 3.2.7 on 2021-09-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
