# Generated by Django 3.2.7 on 2021-09-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
