# Generated by Django 3.2.7 on 2021-09-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210930_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.memberadmin'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
