<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-15 18:03
=======
# Generated by Django 3.2.7 on 2021-09-16 08:39
>>>>>>> 239b3ea9cb87d0ca2c5856ba1d1875078b63d343

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210915_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='main',
            table='main_main',
        ),
    ]
