# Generated by Django 3.2.7 on 2021-09-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_main_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=45)),
                ('event_location', models.CharField(max_length=45)),
                ('event_reporting_date', models.DateField()),
                ('event_views', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.event')),
                ('event_management', models.CharField(blank=True, max_length=45, null=True)),
                ('event_period_start', models.DateField(blank=True, null=True)),
                ('event_period_end', models.DateField(blank=True, null=True)),
                ('event_url', models.CharField(blank=True, max_length=45, null=True)),
                ('event_image_url', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'event_detail',
                'managed': False,
            },
        ),
    ]
