# Generated by Django 3.2.7 on 2021-09-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210917_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_content', models.TextField()),
                ('notice_views', models.IntegerField()),
                ('notice_reporting_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
    ]
