# Generated by Django 3.2.7 on 2021-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
    ]
