# Generated by Django 3.2.7 on 2021-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210918_1308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
