# Generated by Django 3.2.7 on 2021-09-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210918_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
