# Generated by Django 3.2.7 on 2021-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_notice_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='member',
            field=models.CharField(max_length=45),
        ),
    ]
