# Generated by Django 3.2.7 on 2021-09-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notice_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.memberadmin'),
        ),
    ]
