# Generated by Django 3.2.7 on 2021-09-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_notice_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventdetail',
            options={},
        ),
    ]
